### ISSUE TITLE
don't impute missing sites when phasing without reference

### ISSUE THREAD

**Issue by jessehoff** [poruloh/Eagle#13]
can you add an option to avoid doing imputation with phasing without a reference? working in a scenario with different genotyping assays, but want to phase shared sites simultaneously. I have implemented a work around to filter those sites afterwards, but its bit of a pain. 

Thanks!

**Comment by poruloh** [comment]
I believe this option is already implemented:

5.1.3 Missing data treatment

Missing imputation can be turned off using the --noImpMissing option, in which case these genotypes will be left as ./. in the output VCF/BCF.

**Comment by jessehoff** [comment]
I think the last time I tried it when phasing without reference it threw an error. 

4 Phasing without a reference panel

4.1.3 Missing data treatment

Missing genotypes are automatically imputed during the phasing process; the phased haplotypes that Eagle outputs contain best-guess imputed (haploid) genotypes.

**Comment by jessehoff** [comment]
Definitely not a huge issue, but if its not hard to implement under both cases would be a nice option. 

Thanks!

**Comment by poruloh** [comment]
Oops, reading too quickly -- yes, you are right. When phasing without a reference, Eagle has no option to turn off missing imputation. During phasing, Eagle has to maintain a current set of best-guess haplotypes with no missing values, so unfortunately it isn't a trivial fix to turn off the missing imputation. (However, it wouldn't be hard to re-read the genotype data and mask missing values in post-processing, as I assume you're currently doing.)

I'm pretty swamped right now with other projects but will hope to return to this issue eventually.

**Comment by jessehoff** [comment]
No worries. And yes, that masking is exactly what we do. 

It seems that our performance when phasing different assays in this manner is pretty good, and that we're benefitting from the expanded data set. The model is quite a bit slower with all the missing data though (it seems).
