### ISSUE TITLE
out of order SNPS

### ISSUE THREAD

**Issue by flinz** [poruloh/Eagle#14]
Hi there,

I am trying to phase some data from plink files and geta warning that ~100 / 600k SNPS are out of order. It seems like these might correspond to multi-allelic SNPs that I have split into two entries with different alleles, at the same positions. As far as I understand from the documentation, these should be supported. 

Any hints on resolving this?
Thank you!

**Comment by poruloh** [comment]
Apologies for the slow response. You are correct; the warning message is incorrectly printed when multi-allelic SNPs are split into entries with the same position. I will fix this bug in the next release; for now, you can safely ignore the warning.
