### ISSUE TITLE
Question on feature change impact on performance and trio phasing

### ISSUE THREAD

**Issue by hguturu** [poruloh/Eagle#15]
I noticed in Eagle V2.4, the following change was made "Added --pbwtOnly option that skips non-PBWT iterations in non-reference mode (automatically set when N>200K). ". So when cohort phasing large samples the first two steps of doing LRP and then 2 rounds of PBWT have been replaced with 3 rounds of PBWT. Is there any information on phasing accuracy with this change? Was this done purely for computational feasibility? Is there a way to force this off?

Additionally, I noticed Eagle seems to support trio phasing, but the information is not actually used when present in a fam. Can this be exposed as a flag? Or does cohort phasing achieve this means anyways?

**Comment by hguturu** [comment]
Thanks. That is good to know. Did you also see any saturation of performance as you tried larger cohorts? E.g. 200k samples vs. 500k vs 1M if the phasing performance tended to converge to some minima?

**Comment by poruloh** [comment]
I have not observed saturation of performance with increasing cohort size. The largest cohort I have analyzed is UK Biobank N=500K, and accuracy steadily increases throughout the sample size range. I believe this behavior is expected given that the larger the cohort, the greater the chance of finding long IBD between samples.

**Comment by hguturu** [comment]
Thanks for the feedback. I will try to push up the sample size as high as it would be reasonable for compute even when using only PBWT iterations.
