### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by cadunesp** [poruloh/Eagle#17]
Dear Loh,

I’m very new in haplotypes analysis, and I’m trying to run Eagle v2.4. However, I get an error message:

data/frigeriodominc/software/eagle_v2.4/eagle \
    --bfile=brpd11h \
    --geneticMapFile=genetic_map_hg38_withX.txt.gz \
    --Kpbwt=20000 \
    --numThreads=16 \
    --outPrefix=brpd11h 

Setting number of threads to 16

=== Reading genotype data ===

Reading fam file: brpd11h.fam
Total indivs in PLINK data: Nbed = 17
Total indivs stored in memory: NpreQC = 17
Reading bim file: brpd11h.bim
Total snps in PLINK data: Mbed = 247
Total SNPs stored in memory: MpreQC = 247
Filling in genetic map coordinates using reference file:
  genetic_map_hg38_withX.txt.gz
Allocating 247 x 17 bytes to temporarily store genotypes
Reading genotypes and performing QC filtering on snps and indivs...
Reading bed file: brpd11h.bed
    Expecting 1235 (+3) bytes for 17 indivs, 247 snps
Filtering snp rs116807371: 0.352941 missing
Filtering snp rs45554335: 0.352941 missing
Filtering snp rs114069700: 0.352941 missing
Filtering snp rs7921186: 0.352941 missing
Filtering snp rs12217617: 0.352941 missing
Filtered 247 SNPs with > 0.1 missing
Filtering indiv BRPD11 BRPD11_01: 0/0 missing
Filtering indiv BRPD11 BRPD11_02: 0/0 missing
Filtering indiv BRPD11 BRPD11_03: 0/0 missing
Filtering indiv BRPD11 BRPD11_04: 0/0 missing
Filtering indiv BRPD11 BRPD11_05: 0/0 missing
Filtered 17 indivs with > 0.1 missing

Total post-QC indivs: N = 0
Total post-QC SNPs: M = 0
MAF spectrum: 
/var/spool/slurm/slurmd/job7838725/slurm_script: line 8: 12129 Segmentation fault      /data/frigeriodominc/software/eagle_v2.4/eagle --bfile=brpd11h --geneticMapFile=genetic_map_hg38_withX.txt.gz --Kpbwt=20000 --numThreads=16 --outPrefix=brpd11h

My commands are:
First in PLINK/1.9: --ped .ped –map .map –make-bed

Second Eagle v2.4: 

#!/bin/bash
cd /data/frigeriodominc/haplo-est/split-vcf
/data/frigeriodominc/software/eagle_v2.4/eagle \
--bfile=brpd11h \
--geneticMapFile=genetic_map_hg38_withX.txt.gz \
--Kpbwt=20000 \
--numThreads=16 \
--outPrefix=brpd11h

I trying to fix this problem many times but seems not working. Could you please help me and suggest some solution?
I really appreciate your help.
Thanks a lot
Carlos

**Comment by poruloh** [comment]
The problem is that no SNPs or samples passed QC (due to high missingness, as indicated in the output). I will add a check in the next release to print an error message in this situation.
