### ISSUE TITLE
Make htslib IO Parallel

### ISSUE THREAD

**Issue by daheise** [poruloh/Eagle#19]
htslib support parallel read/writes to bgzip files. Currently, eagle is not making use of that functionality. 

I have a use case where parallel IO will result in significant performance improvement, and I can contribute a PR to enable this functionality. However, I will need help regression testing.

**Comment by daheise** [comment]
My editor deleted a lot of extraneous whitespace. Places of interest in the diff are primarily the following:

* https://github.com/poruloh/Eagle/pull/20/files#diff-ebbd328b55ea0c371fa2138c138bf483R3239
* https://github.com/poruloh/Eagle/pull/20/files#diff-ebbd328b55ea0c371fa2138c138bf483R3379
* https://github.com/poruloh/Eagle/pull/20/files#diff-ebda39f44b928af024c25643e1a2a65bR691
* https://github.com/poruloh/Eagle/pull/20/files#diff-7b444dea297629b9284af277a38c621aR224

**Comment by poruloh** [comment]
Thanks again for your help. This improvement is now in the v2.4.1 update.
