### ISSUE TITLE
Build Issue: memcpy.o

### ISSUE THREAD

**Issue by daheise** [poruloh/Eagle#21]
I get the following issue when building:

```
make: *** No rule to make target `memcpy.o', needed by `eagle'.  Stop.
```

The issue is resolved by removing `memcpy.o` from [this line](https://github.com/poruloh/Eagle/blob/master/src/Makefile#L99).

**Comment by poruloh** [comment]
Thanks for pointing out this issue. It slipped in when I added a memcpy.cpp file recently to push down GLIBC dependencies but didn't commit it. This change is probably only relevant for increasing portability of the static binary, but perhaps I should just commit memcpy.cpp? Let me know what you think.


memcpy.cpp:

asm (".symver memcpy, memcpy@GLIBC_2.2.5");

extern "C" void *__wrap_memcpy(void *dest, const void *src, size_t n)
{
  return memcpy(dest, src, n);
}

**Comment by daheise** [comment]
That seems like a fine solution too; I just found a fix on my end that worked and wanted to bring it up.

**Comment by poruloh** [comment]
Ok, I've added the memcpy.cpp file. Thanks for reporting the issue.
