### ISSUE TITLE
Multi-allelic/monomorphic SNPs in ref are misreported

### ISSUE THREAD

**Issue by feuerbach** [poruloh/Eagle#3]
When `tgt->n_allele != 2`, this is reported as either multi-allelic or monomorphic SNP.

But when `ref->n_allele != 2`, this is reported as a "SNP with REF/ALT matching errors". This was rather confusing to us, because we didn't expect any matching errors in our data.

Would you be willing to change the way this is reported? I could prepare a pull request if it helps.

**Comment by poruloh** [comment]
Hi Roman,

Thanks for these reports. I'm currently traveling but aim to make the fixes
when I return late next week. Will be in touch.

Po-Ru

--
Po-Ru Loh
Postdoctoral Research Associate
Department of Epidemiology
Harvard T.H. Chan School of Public Health
655 Huntington Ave, Bldg 2, Rm 209
Boston, MA 02115
http://www.hsph.harvard.edu/po-ru-loh/

**Comment by feuerbach** [comment]
Awesome, thank you.

**Comment by poruloh** [comment]
I have finally updated the error-reporting in the release I just pushed (v2.3.1); apologies for the very long delay.
