### ISSUE TITLE
Phasing SVs

### ISSUE THREAD

**Issue by jjfarrell** [poruloh/Eagle#30]
Does eagle phasing accept VCFs with structural variants?   SVs are often represented with an ALT allele of `<DEL> <INS> <DUP>. `The ref is sometimes set to "N" depending on the SV caller.  

Or would the REF and ALT need to be filled in with the sequence?  Although most are 50-500 regions, the ALT and REF alleles will include variants with 1000s of bp.

**Comment by poruloh** [comment]
Yes, Eagle ignores the contents of the REF and ALT fields, so it will accept a VCF file containing SVs. (If an SV spans other variants in the VCF, then the phased output could include some impossible haplotype configurations, as is also the case with multi-allelic variants.)
