### ISSUE TITLE
ERROR: Failed to allocate 18446744073709551596 bytes

### ISSUE THREAD

**Issue by shafayetrahat** [poruloh/Eagle#33]
Command to reproduce
- eagle --vcf NA20298_snps_chr2.vcf.gz  --geneticMapFile genetic_map_hg19_withX.txt.gz --outPrefix phased_chr2 --chrom 2
Gives me error

Phasing samples 1-1
WARNING: Sample 1 (1-indexed) has a het count of 0
ERROR: Failed to allocate 18446744073709551596 bytes
What causes the error?

**Comment by tgong1** [comment]
Hi,

I'm recently using eagle and getting the same error message. Have you sorted this out?

Thank you for the help!
Tingting

**Comment by AkshajD** [comment]
I am also running into this error. @shafayetrahat has it been resolved for you, and if so, any tips you can share?

Thanks a lot,
Akshaj

**Comment by shafayetrahat** [comment]
Sorry, I couldn't reply early. 
I couldn't solve it and forced to use SHAPEIT instead of EAGLE.
