### ISSUE TITLE
Monomorphic SNPs in target are misreported

### ISSUE THREAD

**Issue by feuerbach** [poruloh/Eagle#4]
If in the target vcf `ALT == "."`, the line will be classified by htslib as `VCF_REF`, and this wouldn't get reported to Eagle unless we set `sr->collapse` to `COLLAPSE_ANY`. So this gets reported as a target-not-in-reference SNP (also the other way around), which is confusing, because the SNP is certainly present in the reference.

**Comment by poruloh** [comment]
I have finally updated the error-reporting in the release I just pushed (v2.3.1); apologies for the very long delay.
